language: ruby
script: bundle exec rake spec

rvm:
  - 1.9.3
  - 2.3.0
gemfile:
  - gemfiles/ruby230.gemfile
  - gemfiles/ruby193.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/ruby230.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/ruby193.gemfile

sudo: false
cache: bundler
